/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "blackColorChip": { "creationFunction": "CreatePushButton", "initialHeight": 28, "initialWidth": 30, "leftImageWidth": 1, "onclick": "colorChanged", "rightImageWidth": 1 },
    "blueColorChip": { "creationFunction": "CreatePushButton", "initialHeight": 28, "initialWidth": 30, "leftImageWidth": 1, "onclick": "colorChanged", "rightImageWidth": 1 },
    "done": { "creationFunction": "CreatePushButton", "initialHeight": 30, "initialWidth": 49, "leftImageWidth": 5, "onclick": "flipToFront", "rightImageWidth": 5, "text": "Done" },
    "familyTitle": { "creationFunction": "CreateText", "text": "Font" },
    "fontColor": { "creationFunction": "CreateText", "text": "Color" },
    "greenColorChip": { "creationFunction": "CreatePushButton", "initialHeight": 28, "initialWidth": 30, "leftImageWidth": 1, "onclick": "colorChanged", "rightImageWidth": 1 },
    "infoButton": { "creationFunction": "CreatePushButton", "customImage": "Images/info.png", "customImagePosition": "PushButton.IMAGE_POSITION_CENTER", "customImagePressed": "Images/info_clicked.png", "initialHeight": 40, "initialWidth": 40, "leftImageWidth": 1, "onclick": "flipToSettings", "rightImageWidth": 1 },
    "purpleColorChip": { "creationFunction": "CreatePushButton", "initialHeight": 28, "initialWidth": 30, "leftImageWidth": 1, "onclick": "colorChanged", "rightImageWidth": 1 },
    "redColorChip": { "creationFunction": "CreatePushButton", "initialHeight": 28, "initialWidth": 30, "leftImageWidth": 1, "onclick": "colorChanged", "rightImageWidth": 1 },
    "reset": { "creationFunction": "CreatePushButton", "initialHeight": 33, "initialWidth": 157, "leftImageWidth": 5, "onclick": "clearSettings", "rightImageWidth": 5, "text": "Clear Settings" },
    "sizeTitle": { "creationFunction": "CreateText", "text": "Size" },
    "text": { "creationFunction": "CreateText", "text": "Settings" },
    "text1": { "creationFunction": "CreateText", "text": "Copyright Sean Kennedy, 2009" },
    "text2": { "creationFunction": "CreateText", "text": "Amount of Data to Move:" },
    "text3": { "creationFunction": "CreateText", "text": "Over Transport:" },
    "text4": { "creationFunction": "CreateText", "text": "Time Required to move the data:" },
    "text_days_label": { "creationFunction": "CreateText", "text": "days:" },
    "text_days_label1": { "creationFunction": "CreateText", "text": "100%" },
    "text_days_label2": { "creationFunction": "CreateText", "text": "75%" },
    "text_hours_label": { "creationFunction": "CreateText", "text": "hours:" },
    "text_minutes_label": { "creationFunction": "CreateText", "text": "minutes:" },
    "title": { "creationFunction": "CreateText", "text": "Transport Speed Calculator" },
    "views": { "creationFunction": "CreateStackLayout", "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "flip" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "flip" }] }
};
